### ISSUE TITLE
Chrome binary not found 

### ISSUE THREAD

**Issue by vincentwhales** [heroku/heroku-buildpack-chromedriver#5]
I am getting the following problem in my heroku app: 

    2017-08-01 20:54:22 ac744713-8102-4c83-81fc-b4be4786b925 selenium.webdriver.remote.remote_connection[4] DEBUG Finished Request
    Traceback (most recent call last):
      File "manage.py", line 89, in <module>
        manager.run()
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
        result = self.handle(sys.argv[0], sys.argv[1:])
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
        res = handle(*args, **config)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
        return self.run(*args, **kwargs)
      File "manage.py", line 83, in cron
        d.main()
      File "/app/blackbird/domain/cron.py", line 58, in main
        self.take_screenshots()
      File "/app/blackbird/domain/cron.py", line 208, in take_screenshots
        self.driver = webdriver.Chrome('chromedriver')
      File "/app/.heroku/python/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
        desired_capabilities=desired_capabilities)
      File "/app/.heroku/python/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
        self.start_session(desired_capabilities, browser_profile)
      File "/app/.heroku/python/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/app/.heroku/python/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
        self.error_handler.check_response(response)
      File "/app/.heroku/python/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
      (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 3.13.0-123-generic x86_64)

even though I have added the chrome driver and the google-chrome buildpacks:

[![enter image description here][1]][1]

Is there a step that I am missing to make my chrome binary available to my app? 

  [1]: https://i.stack.imgur.com/ev99b.png

**Comment by neuman** [comment]
I'm having the same problem.

**Comment by kmcurry** [comment]
My app is Node.js but same issue

**Comment by jdzero** [comment]
You need to make sure to update the binary to the shim when you configure the driver to run.  Pseudo-code:

chrome_options= webdriver.ChromeOptions()
chrome_options.binary_location = env.get('GOOGLE_CHROME_SHIM')
browser = webdriver.Chrome(chrome_options=chrome_options)

**Comment by edmorley** [comment]
Closing stale issues. If the issue persists with the latest version of the buildpack please open a new issue with a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) (but also bear in mind that this buildpack is not an officially supported buildpack, so unless there is an actual bug with the buildpack, application debugging issues are generally out of scope).
